// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTHqjiH3nawZwF_t93l1gmqS9tkL9sX1g',
    appId: '1:15273657880:web:38a789417bc5b50d06256d',
    messagingSenderId: '15273657880',
    projectId: 'asia-webapp-total',
    authDomain: 'asia-webapp-total.firebaseapp.com',
    databaseURL: 'https://asia-webapp-total-default-rtdb.firebaseio.com',
    storageBucket: 'asia-webapp-total.firebasestorage.app',
    measurementId: 'G-BMJMJ2BBEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFzLh2pBzoZ_czMYnef41sCdi39fhI4A',
    appId: '1:15273657880:android:62f24e8febef5b2706256d',
    messagingSenderId: '15273657880',
    projectId: 'asia-webapp-total',
    databaseURL: 'https://asia-webapp-total-default-rtdb.firebaseio.com',
    storageBucket: 'asia-webapp-total.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkh4xr4dOb7j10WBrfjrjblu1FgxaPSgo',
    appId: '1:15273657880:ios:b65b997cf275108706256d',
    messagingSenderId: '15273657880',
    projectId: 'asia-webapp-total',
    databaseURL: 'https://asia-webapp-total-default-rtdb.firebaseio.com',
    storageBucket: 'asia-webapp-total.firebasestorage.app',
    iosClientId: '15273657880-6ns048bdn4o05mksj6o065n04bt0rcbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkh4xr4dOb7j10WBrfjrjblu1FgxaPSgo',
    appId: '1:15273657880:ios:b65b997cf275108706256d',
    messagingSenderId: '15273657880',
    projectId: 'asia-webapp-total',
    databaseURL: 'https://asia-webapp-total-default-rtdb.firebaseio.com',
    storageBucket: 'asia-webapp-total.firebasestorage.app',
    iosClientId: '15273657880-6ns048bdn4o05mksj6o065n04bt0rcbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTHqjiH3nawZwF_t93l1gmqS9tkL9sX1g',
    appId: '1:15273657880:web:df91f0351fb3d26d06256d',
    messagingSenderId: '15273657880',
    projectId: 'asia-webapp-total',
    authDomain: 'asia-webapp-total.firebaseapp.com',
    databaseURL: 'https://asia-webapp-total-default-rtdb.firebaseio.com',
    storageBucket: 'asia-webapp-total.firebasestorage.app',
    measurementId: 'G-E6W3969N19',
  );
}
