// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlIixQCXJGx_Z2T9NpACmZiwswMzEHt4',
    appId: '1:203447599197:web:8417100380b38537b00db4',
    messagingSenderId: '203447599197',
    projectId: 'to-postgres-88ff6',
    authDomain: 'to-postgres-88ff6.firebaseapp.com',
    storageBucket: 'to-postgres-88ff6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl6uoUdfKd144elKMNvaFZZ9eegI5zDKU',
    appId: '1:203447599197:android:a4f6ae24425adfd6b00db4',
    messagingSenderId: '203447599197',
    projectId: 'to-postgres-88ff6',
    storageBucket: 'to-postgres-88ff6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_qCnnJh0k5FxdL0X0Jy6JdRL6_WOBCg',
    appId: '1:203447599197:ios:87eef8cd5a02b257b00db4',
    messagingSenderId: '203447599197',
    projectId: 'to-postgres-88ff6',
    storageBucket: 'to-postgres-88ff6.firebasestorage.app',
    iosClientId: '203447599197-niotr417ut97ltor94mrpq3s3vu2n51b.apps.googleusercontent.com',
    iosBundleId: 'com.example.toPostgres',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_qCnnJh0k5FxdL0X0Jy6JdRL6_WOBCg',
    appId: '1:203447599197:ios:87eef8cd5a02b257b00db4',
    messagingSenderId: '203447599197',
    projectId: 'to-postgres-88ff6',
    storageBucket: 'to-postgres-88ff6.firebasestorage.app',
    iosClientId: '203447599197-niotr417ut97ltor94mrpq3s3vu2n51b.apps.googleusercontent.com',
    iosBundleId: 'com.example.toPostgres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlIixQCXJGx_Z2T9NpACmZiwswMzEHt4',
    appId: '1:203447599197:web:d7c64e81fc6e7b70b00db4',
    messagingSenderId: '203447599197',
    projectId: 'to-postgres-88ff6',
    authDomain: 'to-postgres-88ff6.firebaseapp.com',
    storageBucket: 'to-postgres-88ff6.firebasestorage.app',
  );
}
